version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 599642401641.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=599642401641.dkr.ecr.us-east-1.amazonaws.com/cicdpipeline
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Building the application"
      - mvn clean package
      - echo "Building the Docker image"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'


